FROM rust:1.67 as builder
WORKDIR /usr/src/replay-load-test
COPY . .
RUN cargo build --release

FROM debian:bullseye-slim
COPY --from=builder /usr/src/replay-load-test/target/release/replay-load-test /usr/local/bin/replay-load-test
CMD ["replay-load-test"]