version: "3"

services:
  bin-web-app:
    build:
      context: ./scripts/bin-web-app
    ports:
      - '8080:8080'
  replay-load-test:
    depends_on:
      - bin-web-app
    build:
      context: .
      dockerfile: Dockerfile.deno
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=sqlite://./data/db.sqlite
    volumes:
      - .:/app
