name: Evaluate (Node)

on:
  push:
    branches:
      - main
    paths:
      - node/**
      - .github/workflows/**
  workflow_dispatch:

jobs:
  run-load-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Would like to install snyth and generate fake data via docker compose but gh actions
        # does not like compose volumes, so manually generate it here instead
      - name: Install synth
        run: curl --proto "=https" --tlsv1.2 -sSL https://getsynth.com/install | sh -s -- --ci
      - name: Generate fake data
        run: |
          NUM=300000
          echo "Testing against $NUM records" >> $GITHUB_STEP_SUMMARY
          mkdir data
          cd scripts/generate-fake-data
          synth generate . --collection logs --size $NUM --to json:./test-data.json
          mv ./test-data.json ../../data/test-data.json
      - name: Remove lines from docker compose
        run: yq eval -i 'del(.services."generate-fake-data") | del(.services.replay-load-test.depends_on[1]) | del(.services.replay-load-test.volumes) | del(.volumes)' docker-compose.yaml
      - name: Run docker compose
        run: |
          yq -i '.services.replay-load-test.build.dockerfile = "Dockerfile.node"' docker-compose.yaml
          docker compose up --exit-code-from replay-load-test
      - name: Point container logs to summary
        run: docker logs $(docker container ls --all  | grep 'replay-load-test-replay-load-test' | awk '{print $1}') >> $GITHUB_STEP_SUMMARY
