name: Evaluate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-load-test:
    runs-on: ubuntu-latest
    container:
      volumes:
        - test-data:/volume_mount
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run docker compose
        run: docker compose up
      - name: Point container logs to summary
        run: docker logs $(docker container ls --all  | grep 'replay-load-test-replay-load-test' | awk '{print $1}') >> $GITHUB_STEP_SUMMARY